{
 "title": "Validator Monitoring Metrics",
 "description": "InfluxDB dashboards for telegraf metrics",
 "tags": [
  "influxdb",
  "telegraf"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   { "name": "inter", "label": "Sampling", "query": "10s,30s,1m,2m,5m,10m,30m,1h" },
   {
    "name": "server",
    "label": "Server",
    "query": "SHOW TAG VALUES FROM system WITH KEY=host"
   },
   {
    "name": "mountpoint",
    "label": "Mountpoint",
    "query": "SHOW TAG VALUES FROM \"disk\" WITH KEY = \"path\" WHERE host =~ /$server/"
   },
   {
    "name": "cpu",
    "label": "CPU",
    "query": "SHOW TAG VALUES FROM \"cpu\" WITH KEY = \"cpu\" WHERE host =~ /$server/"
   },
   {
    "name": "disk",
    "label": "Disk",
    "query": "SHOW TAG VALUES FROM \"diskio\" WITH KEY = \"name\" WHERE host =~ /$server/"
   },
   {
    "name": "netif",
    "label": "Network interface",
    "query": "SHOW TAG VALUES FROM \"net\" WITH KEY = \"interface\" WHERE host =~ /$server/"
   }
  ]
 },
 "panels": [
  { "title": "Validator Identity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Validator Details",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "measurement": "vcf_validator_desc",
     "query": "SELECT last(\"val\") AS \"moniker\" FROM \"vcf_validator_desc\" WHERE (\"tag\" = 'moniker') AND $timeFilter",
     "select": [
      [
       { "params": [ "val" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Moniker" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "tag", "operator": "=", "value": "moniker" }
     ]
    },
    {
     "measurement": "vcf_validator_desc",
     "query": "SELECT last(\"value\") AS \"website\" FROM \"vcf_validator_desc\" WHERE (\"tag\" = 'website') ",
     "select": [
      [
       { "params": [ "val" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Website" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "tag", "operator": "=", "value": "website" }
     ]
    },
    {
     "measurement": "vcf_validator_desc",
     "select": [
      [
       { "params": [ "val" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Keybase Identity" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "tag", "operator": "=", "value": "identity" }
     ]
    },
    {
     "measurement": "vcf_validator_desc",
     "select": [
      [
       { "params": [ "val" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Details" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "tag", "operator": "=", "value": "details" }
     ]
    }
   ]
  },
  {
   "title": "Operator Address",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "vcf_operator_address",
     "select": [
      [
       { "params": [ "address" ], "type": "field" },
       { "params": [ "operator address" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Account Address",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "vcf_address",
     "select": [
      [
       { "params": [ "address" ], "type": "field" },
       { "params": [ "address" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  { "title": "Validator Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Meled Status",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "vcf_meled_status",
     "select": [
      [
       { "params": [ "status" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Validator Status",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "vcf_validator_status",
     "select": [
      [
       { "params": [ "status" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Meled Version",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "vcf_meled_version",
     "select": [
      [
       { "params": [ "v" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Validator Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Validator Caught Up",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "vcf_node_synced",
     "select": [
      [
       { "params": [ "status" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Block Time Difference",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 15 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "measurement": "vcf_block_time_diff",
     "select": [
      [
       { "params": [ "time_diff" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Block Height - Validator",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "vcf_current_block_height",
     "select": [
      [
       { "params": [ "height" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Latest Block Height - Network",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "vcf_network_latest_block",
     "select": [
      [
       { "params": [ "block_height" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "height" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Height Difference",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "vcf_height_difference",
     "select": [
      [
       { "params": [ "difference" ], "type": "field" },
       { "params": [ "height_difference" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last Missed Block Range",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "vcf_continuous_missed_blocks",
     "select": [
      [
       { "params": [ "range" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Blocks Missed In Last 48hrs",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "vcf_total_missed_blocks",
     "select": [
      [
       { "params": [ "block_height" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Unconfirmed Txs",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "vcf_unconfirmed_txns",
     "select": [
      [
       { "params": [ "unconfirmed_txns" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Validator Connectivity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "No. of Peers",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "vcf_num_peers",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Peer Addresses",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 9, "x": 4, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "vcf_peer_addresses",
     "select": [
      [
       { "params": [ "addresses" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "addresses_count", "operator": "!=", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "peer_address" ], "type": "tag" }
     ],
     "measurement": "vcf_validator_latency",
     "select": [
      [
       { "params": [ "avg_rtt" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Validator Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Validator Fee",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 35 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "measurement": "vcf_validator_fee",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max Change Rate",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 35 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "measurement": "vcf_validator_max_change_rate",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max Rate",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 35 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "measurement": "vcf_validator_max_rate",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Voting Power",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 35 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "vcf_voting_power",
     "select": [
      [
       { "params": [ "power" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Self Delegation Balance",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 35 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "vcf_self_delegation_balance",
     "select": [
      [
       { "params": [ "balance" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Balance",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 40 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "vcf_account_balance",
     "select": [
      [
       { "params": [ "balance" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Unclaimed Rewards",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 40 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "vcf_current_rewards_amount",
     "select": [
      [
       { "params": [ "amount" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last Proposed Block Height",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 40 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "vcf_last_proposed_block",
     "select": [
      [
       { "params": [ "height" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last Proposed Block Time",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 40 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "vcf_last_proposed_block",
     "select": [
      [
       { "params": [ "block_time" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Proposals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Voting Period Proposals",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "measurement": "vcf_proposals",
     "select": [
      [
       { "params": [ "proposal_id" ], "type": "field" },
       { "params": [ "Prposal ID" ], "type": "alias" }
      ],
      [
       { "params": [ "content_value_title" ], "type": "field" },
       { "params": [ "Proposal Title" ], "type": "alias" }
      ],
      [
       { "params": [ "proposal_status" ], "type": "field" },
       { "params": [ "Proposal Status" ], "type": "alias" }
      ],
      [
       { "params": [ "validator_voted" ], "type": "field" },
       { "params": [ "Validator Vote Status" ], "type": "alias" }
      ],
      [
       { "params": [ "voting_start_time" ], "type": "field" },
       { "params": [ "Voting Start Time" ], "type": "alias" }
      ],
      [
       { "params": [ "voting_end_time" ], "type": "field" },
       { "params": [ "Voting End Time" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "proposal_status", "operator": "=", "value": "VotingPeriod" }
     ]
    }
   ]
  },
  {
   "title": "Deposit Period Proposals",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {
     "measurement": "vcf_proposals",
     "select": [
      [
       { "params": [ "proposal_id" ], "type": "field" },
       { "params": [ "Proposal ID" ], "type": "alias" }
      ],
      [
       { "params": [ "content_value_title" ], "type": "field" },
       { "params": [ "Proposal Title" ], "type": "alias" }
      ],
      [
       { "params": [ "proposal_status" ], "type": "field" },
       { "params": [ "Proposal Status" ], "type": "alias" }
      ],
      [
       { "params": [ "validator_deposited" ], "type": "field" },
       { "params": [ "Validator Deposit Status" ], "type": "alias" }
      ],
      [
       { "params": [ "submit_time" ], "type": "field" },
       { "params": [ "Proposal Submit Time" ], "type": "alias" }
      ],
      [
       { "params": [ "deposit_end_time" ], "type": "field" },
       { "params": [ "Deposit End Time" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "proposal_status", "operator": "=", "value": "DepositPeriod" }
     ]
    }
   ]
  },
  {
   "title": "Completed Proposals",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "measurement": "vcf_proposals",
     "select": [
      [
       { "params": [ "proposal_id" ], "type": "field" },
       { "params": [ "Proposal ID" ], "type": "alias" }
      ],
      [
       { "params": [ "content_value_title" ], "type": "field" },
       { "params": [ "Proposal Title" ], "type": "alias" }
      ],
      [
       { "params": [ "validator_voted" ], "type": "field" },
       { "params": [ "Validator Vote Status" ], "type": "alias" }
      ],
      [
       { "params": [ "proposal_status" ], "type": "field" },
       { "params": [ "Proposal Status" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "proposal_status", "operator": "=", "value": "Passed" },
      { "condition": "OR", "key": "proposal_status", "operator": "=", "value": "Rejected" }
     ]
    }
   ]
  }
 ]
}